services:
  qdrant:
    image: qdrant/qdrant:latest  
    ports:
      - "6333:6333"
    restart: always

  chatbot:
    build:
      context: .                 
      dockerfile: Dockerfile     
    ports:
      - "8080:8080"
    restart: always
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
